apiVersion: apps/v1
kind: Deployment
metadata:
  name: default
  namespace: example
spec:
  replicas: "3"
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: main
