apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: example
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
  labels:
    location/country: USA
    location/state: example
    location/city: example
spec:
  description: example
  initialNodeCount: 3
  location: us-west1
  releaseChannel:
    channel: REGULAR
